# Copyright 2018 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: RHEL subscription
  redhat_subscription:
    state: present
    username: "{{ lookup('env', 'RHSM_USER') }}"
    password: "{{ lookup('env', 'RHSM_PASS') }}"
    auto_attach: true
  when:
    - ansible_distribution == "RedHat"
    - lookup('env', 'RHSM_USER') | length > 0
    - lookup('env', 'RHSM_PASS') | length > 0
    - rhsm_server_hostname == ""
    - rhsm_server_proxy_hostname == ""

- name: RHEL subscription with proxy
  redhat_subscription:
    state: present
    username: "{{ lookup('env', 'RHSM_USER') }}"
    password: "{{ lookup('env', 'RHSM_PASS') }}"
    auto_attach: true
    server_proxy_hostname: "{{ rhsm_server_proxy_hostname | default(omit) }}"
    server_proxy_port: "{{ rhsm_server_proxy_port | default(omit) }}"
  when:
    - ansible_distribution == "RedHat"
    - lookup('env', 'RHSM_USER') | length > 0
    - lookup('env', 'RHSM_PASS') | length > 0
    - rhsm_server_hostname == ""
    - rhsm_server_proxy_hostname != ""

- name: Download Katello CA Consumer RPM from Satellite Server
  get_url:
    url: "http://{{ rhsm_server_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
    dest: /tmp/katello.rpm
    mode: 0755
    owner: root
    group: root
  when:
    - ansible_distribution == "RedHat"
    - rhsm_server_hostname != ""

- name: Install Katello CA Consumer RPM from Satellite Server
  yum:
    name: /tmp/katello.rpm
    state: present
    disable_gpg_check: true
    lock_timeout: 60
  when:
    - ansible_distribution == "RedHat"
    - rhsm_server_hostname != ""

- name: RHEL subscription with satellite using activation key
  redhat_subscription:
    state: present
    activationkey: "{{ lookup('env', 'RHSM_ACTIVATION_KEY') }}"
    org_id: "{{ lookup('env', 'RHSM_ORG_ID') }}"
    server_hostname: "{{ rhsm_server_hostname | default(omit) }}"
    release: "{{ rhsm_server_release_version }}"
  when:
    - ansible_distribution == "RedHat"
    - lookup('env', 'RHSM_ACTIVATION_KEY') | length > 0
    - lookup('env', 'RHSM_ORG_ID') | length > 0
    - rhsm_server_hostname != ""
    - rhsm_server_proxy_hostname == ""

- name: RHEL subscription with satellite and proxy
  redhat_subscription:
    state: present
    activationkey: "{{ lookup('env', 'RHSM_ACTIVATION_KEY') }}"
    org_id: "{{ lookup('env', 'RHSM_ORG_ID') }}"
    server_hostname: "{{ rhsm_server_hostname | default(omit) }}"
    server_proxy_hostname: "{{ rhsm_server_proxy_hostname | default(omit) }}"
    server_proxy_port: "{{ rhsm_server_proxy_port | default(omit) }}"
    release: "{{ rhsm_server_release_version }}"
  when:
    - ansible_distribution == "RedHat"
    - lookup('env', 'RHSM_ACTIVATION_KEY') | length > 0
    - lookup('env', 'RHSM_ORG_ID') | length > 0
    - rhsm_server_hostname != ""
    - rhsm_server_proxy_hostname != ""

- name: Perform dnf clean
  command: /usr/bin/yum -y clean all

- name: Import epel gpg key
  rpm_key:
    state: present
    key: "{{ epel_rpm_gpg_key }}"
  when: epel_rpm_gpg_key != ""

- name: Add epel repo
  yum:
    name: "{{ redhat_epel_rpm }}"
    state: present
    lock_timeout: 60
  when: redhat_epel_rpm != ""

- import_tasks: rpm_repos.yml

- name: Perform a yum update
  yum:
    name: "*"
    state: latest
    exclude: cloud-init*
    lock_timeout: 60

- name: Install baseline dependencies
  yum:
    name: "{{ rpms }}"
    state: present
    lock_timeout: 60

- name: Install extra rpms
  yum:
    name: "{{ extra_rpms.split() }}"
    state: present
    lock_timeout: 60
    disable_gpg_check: true

- name: ensure iptables present for redhat 8
  yum:
    name: "iptables"
    state: present
    lock_timeout: 60
  when: ansible_os_family == "RedHat" and ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: ensure iptables present for redhat 9
  yum:
    name: "iptables-nft"
    state: present
    lock_timeout: 60
  when: ansible_os_family == "RedHat" and ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"
